AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLocalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 300
      CodeUri: mylambda/
      
      Environment:
        Variables:
          TABLE_NAME: !Ref MyChatHistoryTable
          SOURCE_BUCKET: "harinathdocs"

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - "bedrock:InvokeModel"
                - "bedrock:InvokeModelWithResponseStream"
                - "bedrock:ListFoundationModels"
                - "bedrock:GetFoundationModel"
              # Resource '*' బదులు బెడ్‌రాక్ మోడల్స్ ARN ఫార్మాట్ వాడటం మంచిది
              Resource: "arn:aws:bedrock:us-east-1::foundation-model/*"
            
            - Effect: Allow
              Action:
                - "aws-marketplace:ViewSubscriptions"
                - "aws-marketplace:Subscribe"
                - "aws-marketplace:GetEntitlements"
              Resource: "*"

            - Effect: Allow
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:Query"
                - "dynamodb:UpdateItem"
              Resource: !GetAtt MyChatHistoryTable.Arn

            - Effect: Allow
              Action:
                - "s3:GetObject"
                - "s3:ListBucket"
              Resource: 
                - "arn:aws:s3:::harinathdocs"
                - "arn:aws:s3:::harinathdocs/*"

            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"

  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MyLocalFunction
      Principal: s3.amazonaws.com
      SourceArn: "arn:aws:s3:::harinathdocs"

  MyChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyChatHistoryTable
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true